/**
 * Case-study data for the homepage proof grid, the /work index and the
 * /work/[slug] pages. All imagery is real Milktree work living in
 * /public/work/case-studies, generated by scripts/build-case-studies.mjs.
 *
 * `gallery` is a list of rows: one image = full-width moment, two images =
 * a split pair. Every image carries its own descriptive alt text for
 * accessibility and image SEO. `body` is the case-study copy, rendered as
 * paragraphs verbatim.
 */
export type GalleryImage = {
  src: string;
  alt: string;
};

export type WorkProject = {
  slug: string;
  title: string;
  /** Short discipline label for cards and the case-page eyebrow. */
  category: string;
  /** Card image for the proof grids. */
  poster: string;
  /** Full-bleed opening image on the case page. */
  hero: string;
  /** Case-study copy — rendered as paragraphs. */
  body: string[];
  /** Meta description — ≤155 chars, keyword-aware, no template suffix. */
  seoDescription: string;
  services: string[];
  /** Featured projects appear in the homepage proof grid (6 of 12). */
  featured: boolean;
  gallery: GalleryImage[][];
};

const img = (slug: string, name: string) => `/work/case-studies/${slug}/${name}.webp`;

export const workProjects: WorkProject[] = [
  {
    slug: "eazyphone",
    title: "Eazy Phone",
    category: "Brand Identity",
    poster: img("eazyphone", "cards"),
    hero: img("eazyphone", "billboard"),
    body: [
      "We developed a complete brand identity for Eazy Phone, a telecommunications start-up preparing to enter the market. The project focused on giving the business a clear and recognisable identity from the beginning.",
      "The finished brand provided Eazy Phone with a consistent visual foundation that could support the company as it launched and continued to grow.",
    ],
    seoDescription:
      "Brand identity for Eazy Phone: a clear, recognisable identity built from launch for a telecommunications start-up. A Milktree case study.",
    services: ["Brand identity"],
    featured: true,
    gallery: [
      [
        {
          src: img("eazyphone", "cards"),
          alt: "Eazy Phone business cards and stationery in the purple and yellow brand identity",
        },
      ],
      [
        {
          src: img("eazyphone", "bus-stop"),
          alt: "Eazy Phone 'Always in reach' bus stop advertising panel",
        },
        {
          src: img("eazyphone", "lanyards"),
          alt: "Eazy Phone branded staff ID badges and lanyards",
        },
      ],
      [
        {
          src: img("eazyphone", "social"),
          alt: "Eazy Phone social media post designs in the new brand system",
        },
      ],
      [
        {
          src: img("eazyphone", "posters"),
          alt: "Eazy Phone poster campaign displayed on a concrete wall by a stairway",
        },
        {
          src: img("eazyphone", "letterhead"),
          alt: "Eazy Phone branded letterhead with logo and signature",
        },
      ],
      [
        {
          src: img("eazyphone", "screen"),
          alt: "Eazy Phone campaign creative on a large digital screen",
        },
      ],
      [
        {
          src: img("eazyphone", "palette"),
          alt: "Eazy Phone brand colour palette of violet, yellow, white and black",
        },
        {
          src: img("eazyphone", "wordmark"),
          alt: "Eazy Phone wordmark construction and clearspace guidelines",
        },
      ],
    ],
  },
  {
    slug: "mint-mortgages",
    title: "Mint Mortgages",
    category: "Brand & Social",
    poster: img("mint-mortgages", "billboard"),
    hero: img("mint-mortgages", "stationery"),
    body: [
      "We developed a complete brand identity for Mint Mortgages, a UK-based mortgage brand. The project established a clear visual direction that gave the company a consistent and professional presence.",
      "We also created supporting social media graphics, helping Mint Mortgages carry its new identity across its digital communications and marketing content.",
    ],
    seoDescription:
      "Brand identity and social media design for Mint Mortgages: a clear visual direction with a consistent, professional presence. A Milktree case study.",
    services: ["Brand identity", "Social media design"],
    featured: true,
    gallery: [
      [
        {
          src: img("mint-mortgages", "illustration-broker"),
          alt: "Mint Mortgages 'Save more with a local broker' illustrated brand creative",
        },
      ],
      [
        {
          src: img("mint-mortgages", "billboard"),
          alt: "Mint Mortgages 'Simplifying mortgages for you' billboard against a blue sky",
        },
        {
          src: img("mint-mortgages", "doorstep"),
          alt: "Mint Mortgages campaign photography of a new homeowner holding keys on her doorstep",
        },
      ],
      [
        {
          src: img("mint-mortgages", "social-stats"),
          alt: "Mint Mortgages social media graphics with mortgage market statistics",
        },
      ],
      [
        {
          src: img("mint-mortgages", "website-screens"),
          alt: "Mint Mortgages website and social profile screens in the new identity",
        },
      ],
      [
        {
          src: img("mint-mortgages", "illustration-rates"),
          alt: "Mint Mortgages 'Fresh rates, smart moves' illustrated campaign creative",
        },
        {
          src: img("mint-mortgages", "palette"),
          alt: "Mint Mortgages brand colour palette of bright green, dark green and cream",
        },
      ],
      [
        {
          src: img("mint-mortgages", "wordmark"),
          alt: "Mint Mortgages wordmark on a dark green background",
        },
      ],
    ],
  },
  {
    slug: "saints-foundation",
    title: "Saints Foundation",
    category: "Event Design",
    poster: img("saints-foundation", "programme"),
    hero: img("saints-foundation", "main-stage"),
    body: [
      "We produced the graphic design for the Saints Foundation’s annual charity gala. Saints Foundation is the official charity of Southampton Football Club.",
      "The project involved creating event graphics that supported the gala and provided the charity with a consistent visual style for its annual event communications.",
    ],
    seoDescription:
      "Event graphic design for the Saints Foundation charity gala at Southampton FC: programmes, stage graphics and venue branding. By Milktree.",
    services: ["Event graphic design"],
    featured: true,
    gallery: [
      [
        {
          src: img("saints-foundation", "stairs"),
          alt: "Branded stair graphics welcoming guests to the Saints Foundation Charity Dinner",
        },
      ],
      [
        {
          src: img("saints-foundation", "welcome-easel"),
          alt: "Saints Foundation Charity Dinner welcome board on an easel at the venue entrance",
        },
        {
          src: img("saints-foundation", "banner-stand"),
          alt: "Saints Foundation Charity Dinner roller banner in the event identity",
        },
      ],
      [
        {
          src: img("saints-foundation", "media-wall"),
          alt: "Saints Foundation Charity Dinner media wall with repeating partner logos",
        },
      ],
      [
        {
          src: img("saints-foundation", "flyers"),
          alt: "Saints Foundation live auction flyers listing prize lots for the charity dinner",
        },
        {
          src: img("saints-foundation", "programme"),
          alt: "Saints Foundation Charity Dinner event programme cover with radiating-lines motif",
        },
      ],
      [
        {
          src: img("saints-foundation", "dinner-room"),
          alt: "The Saints Foundation Charity Dinner room at St Mary's dressed in the event branding",
        },
      ],
    ],
  },
  {
    slug: "melt",
    title: "Melt",
    category: "Brand Identity",
    poster: img("melt", "box-handoff"),
    hero: img("melt", "food-truck"),
    body: [
      "We developed a complete brand identity for Melt, an independent pizza restaurant. The project focused on creating a distinctive visual direction that reflected the personality of the business and gave the restaurant a recognisable presence.",
      "The finished identity provided Melt with a consistent brand that could be carried across its marketing, communications and customer touchpoints.",
    ],
    seoDescription:
      "Brand identity for Melt Pizza Co: a distinctive visual direction carried across packaging, menus and every customer touchpoint. A Milktree case study.",
    services: ["Brand identity"],
    featured: true,
    gallery: [
      [
        {
          src: img("melt", "boxes-hands"),
          alt: "Melt Pizza Co branded pizza boxes with hands reaching for slices",
        },
      ],
      [
        {
          src: img("melt", "menu-hand"),
          alt: "Customer reading the Melt Pizza Co printed menu",
        },
        {
          src: img("melt", "cap"),
          alt: "Melt Pizza Co branded corduroy cap on a pizza box topping checklist",
        },
      ],
      [
        {
          src: img("melt", "boxes-red"),
          alt: "Melt Pizza Co pizza box designs arranged on a red background",
        },
      ],
      [
        {
          src: img("melt", "open-box"),
          alt: "Open Melt Pizza Co box with checkerboard trim revealing a pizza slice",
        },
        {
          src: img("melt", "oven"),
          alt: "Melt mosaic-tiled pizza oven in the brand red",
        },
      ],
      [
        {
          src: img("melt", "menu-cards"),
          alt: "Melt Pizza Co menu design with pizzas, wings, sides and shakes",
        },
      ],
      [
        {
          src: img("melt", "customers"),
          alt: "Customers sharing a pizza in Melt Pizza Co branded t-shirts",
        },
        {
          src: img("melt", "a-frame"),
          alt: "Melt Pizza Co A-frame menu sign on the pavement",
        },
      ],
      [
        {
          src: img("melt", "illustrations"),
          alt: "Melt Pizza Co hand-drawn brand illustrations of pizza, chef and pizza oven",
        },
      ],
    ],
  },
  {
    slug: "ao",
    title: "AO",
    category: "Brand Identity",
    poster: img("ao", "phone"),
    hero: img("ao", "sign"),
    body: [
      "We created the brand identity for AO, a fine dining experience that has been featured in the Michelin Guide. The project required a visual identity that could represent the quality and attention to detail associated with the restaurant and its dining experience.",
      "The finished brand gave AO a clear and considered visual direction that could be used consistently across its customer-facing materials.",
    ],
    seoDescription:
      "Brand identity for AO, a Michelin Guide fine dining restaurant: a considered visual direction for every customer-facing touchpoint. By Milktree.",
    services: ["Brand identity"],
    featured: true,
    gallery: [
      [
        {
          src: img("ao", "laptop"),
          alt: "AO restaurant website shown on a laptop in low light",
        },
      ],
      [
        {
          src: img("ao", "phone"),
          alt: "AO restaurant mobile website on a phone against textured upholstery",
        },
        {
          src: img("ao", "menu"),
          alt: "AO restaurant printed menu with the root-inspired brand mark",
        },
      ],
      [
        {
          src: img("ao", "website-screens"),
          alt: "AO restaurant website pages with fine dining photography",
        },
      ],
      [
        {
          src: img("ao", "instagram"),
          alt: "AO restaurant Instagram grid with food, chef and interior photography",
        },
      ],
      [
        {
          src: img("ao", "website-booking"),
          alt: "AO restaurant online booking page design",
        },
        {
          src: img("ao", "website-pages"),
          alt: "AO restaurant menu and blog page designs",
        },
      ],
      [
        {
          src: img("ao", "wordmark"),
          alt: "AO restaurant wordmark with root illustration on slate blue",
        },
      ],
    ],
  },
  {
    slug: "remigo",
    title: "Remigo",
    category: "Brand, Web & App",
    poster: img("remigo", "round-sign"),
    hero: img("remigo", "billboard"),
    body: [
      "We developed a complete brand identity for Remigo, a company specialising in remortgages and protection. The project also included the design of the company’s website and app, creating a consistent visual experience across the business.",
      "By developing the brand and digital platforms together, we gave Remigo a clear identity that could be applied consistently throughout its online customer experience.",
    ],
    seoDescription:
      "Brand identity, website and app design for Remigo: one consistent visual experience across the remortgage specialist's business. A Milktree case study.",
    services: ["Brand identity", "Website design", "App design"],
    featured: true,
    gallery: [
      [
        {
          src: img("remigo", "website-laptop"),
          alt: "Remigo website on a laptop resting on a red velvet chair",
        },
      ],
      [
        {
          src: img("remigo", "linkedin-phone"),
          alt: "Remigo LinkedIn company profile on a phone against tan leather",
        },
        {
          src: img("remigo", "round-sign"),
          alt: "Remigo circular R sign mounted on a building facade",
        },
      ],
      [
        {
          src: img("remigo", "fence-banner"),
          alt: "Remigo campaign creative across a large construction fence banner",
        },
      ],
      [
        {
          src: img("remigo", "outdoor-screen"),
          alt: "Remigo out-of-home digital screen with the shredder campaign",
        },
        {
          src: img("remigo", "flag-banner"),
          alt: "Remigo vertical banner hanging between city buildings",
        },
      ],
      [
        {
          src: img("remigo", "business-cards"),
          alt: "Remigo business card front and back on brand red",
        },
      ],
      [
        {
          src: img("remigo", "wordmark"),
          alt: "Remigo wordmark in white with a red dot on black",
        },
      ],
    ],
  },
  {
    slug: "alltrad-roofing",
    title: "Alltrad",
    category: "Brand Identity",
    poster: img("alltrad-roofing", "hard-hat"),
    hero: img("alltrad-roofing", "billboard"),
    body: [
      "Alltrad approached Milktree with an initial idea for a roofing brand that needed to be developed into something clear and professional. We took that early concept and transformed it into a complete brand identity that gave the company a strong foundation to build from.",
      "The finished identity brought consistency and direction to the business, helping Alltrad present itself as an established and recognisable roofing company.",
    ],
    seoDescription:
      "Brand identity for Alltrad Roofing: an early concept developed into a clear, professional identity for a roofing company. A Milktree case study.",
    services: ["Brand identity"],
    featured: false,
    gallery: [
      [
        {
          src: img("alltrad-roofing", "fleece"),
          alt: "Alltrad Roofing logo embroidered on a branded fleece jacket",
        },
      ],
      [
        {
          src: img("alltrad-roofing", "pin-badge"),
          alt: "Alltrad Roofing enamel pin badge of the red chevron mark",
        },
        {
          src: img("alltrad-roofing", "card-hand"),
          alt: "Alltrad Roofing business card held in a hand",
        },
      ],
      [
        {
          src: img("alltrad-roofing", "logo-banner"),
          alt: "Alltrad Roofing logo lockup on the brand red",
        },
      ],
      [
        {
          src: img("alltrad-roofing", "flags"),
          alt: "Alltrad Roofing branded flags mounted on a building",
        },
        {
          src: img("alltrad-roofing", "website-tablet"),
          alt: "Alltrad Roofing website quote form on a tablet",
        },
      ],
      [
        {
          src: img("alltrad-roofing", "bus-stop"),
          alt: "Alltrad Roofing 'Building strong roofs, building trust' bus stop advert",
        },
      ],
      [
        {
          src: img("alltrad-roofing", "hard-hat"),
          alt: "Alltrad Roofing branded hard hat on a red background",
        },
        {
          src: img("alltrad-roofing", "site-banner"),
          alt: "Alltrad Roofing banner on construction site scaffolding",
        },
      ],
      [
        {
          src: img("alltrad-roofing", "social-screens"),
          alt: "Alltrad Roofing social media creatives on a dark background",
        },
      ],
      [
        {
          src: img("alltrad-roofing", "cards-hook"),
          alt: "Alltrad Roofing business cards with the chevron mark",
        },
        {
          src: img("alltrad-roofing", "site-team"),
          alt: "Site team in hi-vis with the Alltrad Roofing app icon",
        },
      ],
    ],
  },
  {
    slug: "ejw-concrete",
    title: "EJW Concrete Structures",
    category: "Brand & Web",
    poster: img("ejw-concrete", "flags"),
    hero: img("ejw-concrete", "built-to-last"),
    body: [
      "We delivered a full brand refresh and website design for EJW Concrete Structures, a concrete structure company operating across the South of England. The project was focused on improving how the business presented itself and creating a more consistent overall identity.",
      "Alongside the refreshed branding, we designed a professional website that gave EJW a stronger digital presence and a clearer platform for showcasing the company and its work.",
    ],
    seoDescription:
      "Brand refresh and website design for EJW Concrete Structures: a consistent identity and stronger digital presence. A Milktree case study.",
    services: ["Brand refresh", "Website design"],
    featured: false,
    gallery: [
      [
        {
          src: img("ejw-concrete", "site-banner"),
          alt: "EJW Concrete Structures construction site banner",
        },
      ],
      [
        {
          src: img("ejw-concrete", "flags"),
          alt: "EJW Concrete Structures branded flags against a blue sky",
        },
        {
          src: img("ejw-concrete", "id-badge"),
          alt: "EJW Concrete Structures site supervisor ID badge and lanyard",
        },
      ],
      [
        {
          src: img("ejw-concrete", "website-laptop"),
          alt: "EJW Concrete Structures website shown on a laptop",
        },
      ],
      [
        {
          src: img("ejw-concrete", "logo-dark"),
          alt: "EJW Concrete Structures logo on a dark navy background",
        },
      ],
    ],
  },
  {
    slug: "latimers",
    title: "Latimers",
    category: "Brand & Launch",
    poster: img("latimers", "bag"),
    hero: img("latimers", "apron"),
    body: [
      "We created the branding and launch creatives for Latimers, an independent restaurant based in Hampshire, UK. The project established a clear visual direction for the restaurant ahead of its launch.",
      "We also developed the creative assets needed to introduce the new brand to its audience, helping Latimers build a consistent and recognisable presence from the beginning.",
    ],
    seoDescription:
      "Branding and launch creatives for Latimers, an independent Hampshire restaurant: a clear visual direction from day one. A Milktree case study.",
    services: ["Branding", "Launch creatives"],
    featured: false,
    gallery: [
      [
        {
          src: img("latimers", "box"),
          alt: "Latimers branded packaging box on a stone surface",
        },
        {
          src: img("latimers", "glass"),
          alt: "Latimers wordmark on the base of a wine glass",
        },
      ],
      [
        {
          src: img("latimers", "menus"),
          alt: "Latimers printed menus in the launch identity",
        },
      ],
      [
        {
          src: img("latimers", "prawn-pasta"),
          alt: "Latimers prawn pasta dish from the brand photography",
        },
        {
          src: img("latimers", "sea-bass"),
          alt: "Latimers sea bass and mussels dish from the brand photography",
        },
      ],
      [
        {
          src: img("latimers", "social"),
          alt: "Latimers launch social media creatives",
        },
      ],
      [
        {
          src: img("latimers", "table"),
          alt: "Latimers branded table setting with brass details",
        },
        {
          src: img("latimers", "bag"),
          alt: "Latimers takeaway paper bag with red handles",
        },
      ],
      [
        {
          src: img("latimers", "illustrations"),
          alt: "Latimers hand-drawn produce illustration pattern",
        },
      ],
      [
        {
          src: img("latimers", "exterior"),
          alt: "The Latimers restaurant exterior at night",
        },
      ],
      [
        {
          src: img("latimers", "tasting-plate"),
          alt: "Latimers squash tasting plate from the brand photography",
        },
        {
          src: img("latimers", "sunday-roast"),
          alt: "Latimers Sunday roast with gravy being poured",
        },
      ],
      [
        {
          src: img("latimers", "wordmark"),
          alt: "Latimers wordmark on the brand rust orange",
        },
      ],
    ],
  },
  {
    slug: "salesprout",
    title: "SaleSprout",
    category: "Brand Identity",
    poster: img("salesprout", "round-sign"),
    hero: img("salesprout", "billboard"),
    body: [
      "We created a complete brand identity for SaleSprout, a software company that needed a clear and consistent visual direction. The project gave the business a professional identity that could support how it communicated and presented itself.",
      "The finished brand created a strong foundation for SaleSprout to use across its digital presence and wider company materials.",
    ],
    seoDescription:
      "Brand identity for SaleSprout: a clear, consistent visual direction for a software company's digital presence and materials. A Milktree case study.",
    services: ["Brand identity"],
    featured: false,
    gallery: [
      [
        {
          src: img("salesprout", "dashboard"),
          alt: "SaleSprout software dashboard on a laptop in the brand green",
        },
      ],
      [
        {
          src: img("salesprout", "card"),
          alt: "SaleSprout business card in the brand green",
        },
        {
          src: img("salesprout", "app-icon"),
          alt: "SaleSprout app icon on a phone home screen",
        },
      ],
      [
        {
          src: img("salesprout", "social"),
          alt: "SaleSprout social media post designs",
        },
      ],
      [
        {
          src: img("salesprout", "guidelines"),
          alt: "SaleSprout brand guidelines cover and identity system",
        },
      ],
    ],
  },
  {
    slug: "powerforce",
    title: "Powerforce Renewables",
    category: "Brand & Web",
    poster: img("powerforce", "cards"),
    hero: img("powerforce", "cards"),
    body: [
      "We created a complete brand identity and website for Powerforce Renewables, a company supplying commercial and domestic solar solutions. The project focused on giving the business a professional and consistent presence across both its branding and digital platforms.",
      "The finished website provided Powerforce Renewables with a clear online platform for presenting the company and its range of solar solutions to commercial and domestic customers.",
    ],
    seoDescription:
      "Brand identity and website design for Powerforce Renewables: a professional, consistent presence for a solar solutions company. By Milktree.",
    services: ["Brand identity", "Website design"],
    featured: false,
    gallery: [
      [
        {
          src: img("powerforce", "guidelines"),
          alt: "Powerforce Renewables brand guidelines spreads",
        },
      ],
      [
        {
          src: img("powerforce", "wall-poster"),
          alt: "Powerforce Renewables 'Helping to build the future' poster on a wall",
        },
        {
          src: img("powerforce", "brand-card"),
          alt: "Powerforce Renewables brand messaging card on dark green",
        },
      ],
      [
        {
          src: img("powerforce", "social"),
          alt: "Powerforce Renewables social media creatives with wind turbine photography",
        },
      ],
      [
        {
          src: img("powerforce", "email"),
          alt: "Powerforce Renewables branded email signature design",
        },
        {
          src: img("powerforce", "palette"),
          alt: "Powerforce Renewables brand colour palette of greens",
        },
      ],
      [
        {
          src: img("powerforce", "logo"),
          alt: "Powerforce Renewables logo with lightning-bolt P mark",
        },
      ],
    ],
  },
  {
    slug: "orange-rooms",
    title: "Orange Rooms",
    category: "Graphic Design",
    poster: img("orange-rooms", "coaster"),
    hero: img("orange-rooms", "menu-spreads"),
    body: [
      "We provided graphic design support for Orange Rooms, an established bar in the UK. The work focused on creating professional visual assets that worked alongside the venue’s existing identity.",
      "Each creative was designed to maintain consistency across the brand while supporting the venue’s ongoing marketing and customer communications.",
    ],
    seoDescription:
      "Graphic design for Orange Rooms, an established UK bar: menus and marketing creatives consistent with the venue's identity. A Milktree case study.",
    services: ["Graphic design"],
    featured: false,
    gallery: [
      [
        {
          src: img("orange-rooms", "cocktails"),
          alt: "Bartender pouring cocktails at Orange Rooms",
        },
        {
          src: img("orange-rooms", "drinks"),
          alt: "Hands holding drinks at the Orange Rooms bar",
        },
      ],
      [
        {
          src: img("orange-rooms", "christmas-menu"),
          alt: "Orange Rooms Christmas buffet menu on a pool table",
        },
      ],
      [
        {
          src: img("orange-rooms", "summer-menu"),
          alt: "Orange Rooms summer menu design with branded coaster",
        },
        {
          src: img("orange-rooms", "coaster"),
          alt: "Orange Rooms branded coaster held in a hand",
        },
      ],
    ],
  },
];

export const featuredWorkProjects = workProjects.filter((p) => p.featured);

export function getWorkProject(slug: string): WorkProject | undefined {
  return workProjects.find((p) => p.slug === slug);
}

export function getNextWorkProject(slug: string): WorkProject {
  const i = workProjects.findIndex((p) => p.slug === slug);
  return workProjects[(i + 1) % workProjects.length];
}
